development: &default
  cloud_name: <%= ENV.fetch('CLOUDINARY_NAME') %>
  api_key: <%= ENV.fetch('CLOUDINARY_API_KEY') %>
  api_secret: <%= ENV.fetch('CLOUDINARY_API_SECRET') %>

test:
  <<: *default

production:
  <<: *default
