default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'mungazi_development' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: mungazi_development

test:
  <<: *default
  database: <%= ENV["JENKINS_DATABASE"] || 'mungazi_test' %>

production:
  <<: *default
